In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.70359296, -0.33141923,  0.24262372, -0.29789013, -0.7646231 ,
        -0.20851903, -0.18930016, -0.4309365 ,  0.38027328,  0.13521713]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.05758974, 0.08355609, 0.14834803, 0.08640514, 0.05418013,
        0.09448285, 0.09631626, 0.07564118, 0.17024024, 0.13324033]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3593369

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8578 - loss: 0.4823
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9540 - loss: 0.1560
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9664 - loss: 0.1126
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9719 - loss: 0.0906
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9747 - loss: 0.0788


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9753 - loss: 0.0816


[0.08163808286190033, 0.9753000140190125]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.16946150e-09, 2.93489588e-08, 6.08149833e-07, 3.97573865e-04,
        8.30141782e-13, 6.60501209e-09, 8.02418163e-14, 9.99600232e-01,
        2.07028620e-07, 1.45539184e-06],
       [2.01732945e-07, 3.78225907e-03, 9.95332897e-01, 8.79909494e-04,
        1.09347684e-14, 4.28453450e-06, 6.53122783e-08, 1.96393466e-12,
        2.30156544e-07, 6.09911020e-14],
       [8.43372277e-07, 9.98313069e-01, 2.34045783e-05, 4.21958321e-05,
        1.10837427e-04, 6.81678739e-06, 1.64494413e-05, 1.20567589e-03,
        2.73506332e-04, 7.18642013e-06],
       [9.99989152e-01, 9.07062064e-11, 7.64331560e-07, 2.83254664e-08,
        3.10371151e-09, 5.10346325e-08, 3.73338207e-06, 3.25663382e-06,
        1.30733901e-09, 2.98582586e-06],
       [1.69072598e-06, 1.92446642e-10, 2.25425947e-06, 4.14418935e-08,
        9.99622703e-01, 3.36465092e-07, 9.91477350e-07, 3.55720076e-05,
        3.61166279e-08, 3.36348166e-04]], dtype=float32)>